name = "newcomer2023-ogp"
main = "src/index.ts"
compatibility_date = "2023-01-01"

kv_namespaces = [
  { binding = "OGP_KV", id = "83392f9da1fa467aabe1b63051a993f1", preview_id = "be8ea5aaf91648938eab044b473e9fc4" }
]
services = [
  { binding = "API", service = "newcomer2023-api" },
]

[env.development]
name = "newcomer2023-ogp-dev"
kv_namespaces = [
  { binding = "OGP_KV", id = "be8ea5aaf91648938eab044b473e9fc4", preview_id = "be8ea5aaf91648938eab044b473e9fc4" }
]
services = [
  { binding = "API", service = "newcomer2023-api-dev" },
]

[vars]
IMGIX_DOMAIN = "studioaquatan.imgix.net"
NEWT_ROOT = "https://storage.googleapis.com/p_63bcc96411c3ecd6f0b5dc8b/"
RESOURCE_URL = "https://newcomer2023-assets.studioaquatan.workers.dev/assets"

[env.development.vars]
IMGIX_DOMAIN = "studioaquatan.imgix.net"
NEWT_ROOT = "https://storage.googleapis.com/p_63bcc96411c3ecd6f0b5dc8b/"
RESOURCE_URL = "https://newcomer2023-assets.studioaquatan.workers.dev/assets"

[[ d1_databases ]]
binding = "DB"
database_name = "newcomer2023"
database_id = "88d9c498-a2f3-4284-b680-1a733416ee69"
preview_database_id = "846cb66e-9c26-4a7d-9250-e3df185ca7b2"

[[ env.development.d1_databases ]]
binding = "DB"
database_name = "newcomer2023-dev"
database_id = "846cb66e-9c26-4a7d-9250-e3df185ca7b2"
preview_database_id = "846cb66e-9c26-4a7d-9250-e3df185ca7b2"

[[ r2_buckets ]]
binding = "ASSETS"
bucket_name = "newcomer2023"
preview_bucket_name = "newcomer2023"

[[ env.development.r2_buckets ]]
binding = "ASSETS"
bucket_name = "newcomer2023"
preview_bucket_name = "newcomer2023"

[[ queues.producers ]]
queue = "newcomer2023-ogp-queue"
binding = "OGP_QUEUE"

[[queues.consumers]]
queue = "newcomer2023-ogp-queue"
max_batch_size = 10
max_batch_timeout = 10
max_retries = 1

[[ env.development.queues.producers ]]
queue = "newcomer2023-ogp-queue-dev"
binding = "OGP_QUEUE"

[[ env.development.queues.consumers ]]
queue = "newcomer2023-ogp-queue-dev"
max_batch_size = 10
max_batch_timeout = 10
max_retries = 1
